---
# tasks file for trusted_certificates
- name: copy ldap certificate to trusted certs folder
  copy:
    src: "/opt/ansible/certificates/{{ top_level_domain }}.crt"
    dest: "/usr/local/share/ca-certificates/{{ top_level_domain }}.crt"
    mode: 0644
  register: result
  become: yes

- name: Update cert index
  command: /usr/sbin/update-ca-certificates
  when: result | changed
  become: yes