---
# tasks file for trusted_certificates
- name: copy ldap certificate to trusted certs folder
  copy:
    src: "/opt/ansible/certificates/public"
    dest: "/usr/local/share/ca-certificates"
    mode: 0644
  register: result
  become: yes

- name: Update cert index
  command: /usr/sbin/update-ca-certificates
  when: result is changed
  become: yes